### ISSUE TITLE
The app crashes on start

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-native-wallet#2]
The `updatePricesContinuously` calls the `delay` function which was recently updated. I've re-installed the packages, still no result.

![screenshot 2019-02-07 at 12 19 30](https://user-images.githubusercontent.com/38855190/52408227-b59d6280-2ad2-11e9-8417-1eae305c2110.png)

**Comment by MiroslavPetrik** [comment]
`delay` is an effect since v1
https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0

We should bump the version, breaking changes should not affect us.

**Comment by Kamahl19** [comment]
yep, i did it in rewrite branch already although forgot to bump in master. please do
