### ISSUE TITLE
Fix (possibly just update) reactotron

### ISSUE THREAD

**Issue by MiroslavPetrik** [Kamahl19/react-native-wallet#4]
After updating the redux-saga package, app still crashes
`Cannot read property 'startedAt' of undefined`

Possibly https://github.com/infinitered/reactotron/issues/917

Commenting the line
https://github.com/Kamahl19/react-native-wallet/blob/6509e3cc28549f6608705aa3d69de553729d5d72/src/app/store/configureStore.dev.js#L13

fixed it

**Comment by Kamahl19** [comment]
just remove reactotron altogether, no need for it

**Comment by MiroslavPetrik** [comment]
I love removing things.
